[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
target-version = "py310"

[tool.ruff.lint]
extend-select = ["I"]  # import sorting

[tool.ruff.lint.isort]
known-first-party = ["app", "tests"]
