name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.12' }
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install -r dev-requirements.txt || true
      - name: Run pre-commit (ruff/black + hygiene)
        run: pre-commit run -a
      - name: Run tests
        run: pytest -q

  build-and-push:
    needs: test-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # allow push to GHCR
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/dev_demo:latest
            ghcr.io/${{ github.repository_owner }}/dev_demo:${{ github.sha }}
